/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VoteInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aVoter"
      | "addVoter"
      | "balanceOf"
      | "candidates"
      | "getCandidat"
      | "getNbCandidat"
      | "isVotant"
      | "name"
      | "owner"
      | "ownerOf"
      | "startVote"
      | "symbol"
      | "totalToken"
      | "vote"
      | "voteOuvert"
      | "voterCandidat"
      | "voterToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Transfer" | "VotantAjouter" | "VoteCommencer"
  ): EventFragment;

  encodeFunctionData(functionFragment: "aVoter", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "addVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "candidates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidat",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNbCandidat",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isVotant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "startVote", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vote", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "voteOuvert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voterCandidat",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voterToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "aVoter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addVoter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "candidates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCandidat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNbCandidat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVotant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voteOuvert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voterCandidat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voterToken", data: BytesLike): Result;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotantAjouterEvent {
  export type InputTuple = [voter: AddressLike];
  export type OutputTuple = [voter: string];
  export interface OutputObject {
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCommencerEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Vote extends BaseContract {
  connect(runner?: ContractRunner | null): Vote;
  waitForDeployment(): Promise<this>;

  interface: VoteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aVoter: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  addVoter: TypedContractMethod<[votant: AddressLike], [void], "nonpayable">;

  balanceOf: TypedContractMethod<[_owner: AddressLike], [bigint], "view">;

  candidates: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { name: string; nb_vote: bigint }],
    "view"
  >;

  getCandidat: TypedContractMethod<
    [idCandidat: BigNumberish],
    [[string, bigint] & { candidateName: string; nb_vote: bigint }],
    "view"
  >;

  getNbCandidat: TypedContractMethod<[], [bigint], "view">;

  isVotant: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  startVote: TypedContractMethod<[], [void], "nonpayable">;

  symbol: TypedContractMethod<[], [string], "view">;

  totalToken: TypedContractMethod<[], [bigint], "view">;

  vote: TypedContractMethod<[candidateId: BigNumberish], [void], "nonpayable">;

  voteOuvert: TypedContractMethod<[], [boolean], "view">;

  voterCandidat: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  voterToken: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aVoter"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "addVoter"
  ): TypedContractMethod<[votant: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[_owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "candidates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { name: string; nb_vote: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCandidat"
  ): TypedContractMethod<
    [idCandidat: BigNumberish],
    [[string, bigint] & { candidateName: string; nb_vote: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNbCandidat"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isVotant"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "startVote"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalToken"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<[candidateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteOuvert"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "voterCandidat"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "voterToken"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "VotantAjouter"
  ): TypedContractEvent<
    VotantAjouterEvent.InputTuple,
    VotantAjouterEvent.OutputTuple,
    VotantAjouterEvent.OutputObject
  >;
  getEvent(
    key: "VoteCommencer"
  ): TypedContractEvent<
    VoteCommencerEvent.InputTuple,
    VoteCommencerEvent.OutputTuple,
    VoteCommencerEvent.OutputObject
  >;

  filters: {
    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "VotantAjouter(address)": TypedContractEvent<
      VotantAjouterEvent.InputTuple,
      VotantAjouterEvent.OutputTuple,
      VotantAjouterEvent.OutputObject
    >;
    VotantAjouter: TypedContractEvent<
      VotantAjouterEvent.InputTuple,
      VotantAjouterEvent.OutputTuple,
      VotantAjouterEvent.OutputObject
    >;

    "VoteCommencer()": TypedContractEvent<
      VoteCommencerEvent.InputTuple,
      VoteCommencerEvent.OutputTuple,
      VoteCommencerEvent.OutputObject
    >;
    VoteCommencer: TypedContractEvent<
      VoteCommencerEvent.InputTuple,
      VoteCommencerEvent.OutputTuple,
      VoteCommencerEvent.OutputObject
    >;
  };
}
